services:
    acme_hello.topic_sample_service:
        class: BmdUserBundle\Topic\AcmeTopic
        tags:
            - { name: gos_web_socket.topic }

    acme_hello.rpc_sample_service:
        class: BmdUserBundle\Rpc\AcmeRpc
        tags:
            - { name: gos_web_socket.rpc }