services:
    acme_hello.topic_sample_service:
        class: BmdUserBundle\Topic\AcmeTopic
        tags:
            - { name: gos_web_socket.topic }

    acme_hello.rpc_sample_service:
        class: BmdUserBundle\Rpc\AcmeRpc
        tags:
            - { name: gos_web_socket.rpc }
    bmduserbundle.calendar_listener: 
        class: BmdUserBundle\EventListener\CalendarEventListener
        arguments: [@doctrine.orm.entity_manager]
        tags: 
            - { name: kernel.event_listener, event: calendar.load_events ,  method: loadEvents} 
    activity_listener:
        class: BmdUserBundle\Listener\ActivityListener
        arguments: [@security.context, @doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }
            