var event1 = {name: "palacio", place: "Rue Maurice Gunsbourg, 94200 Ivry-sur-Seine"};
var event2 = {name: "Le River & Sea", place: "6, Quai Jean Compagnon, Ivry Sur Seine 94200"};
var event3 = {name: "Libertalia", place: "quai n°6 Jean Campagnon 94200 Ivry Sur Seine"};
var event4 = {name: "Get in step", place: "Parc de la Villette, 211 avenue Jean Jaurès, 75019, Paris, France"};
var event5 = {name: "10 years diynamic", place: "32-34 rue Marbeuf, 75008, Paris, France"};
var event6 = {name: "concrete", place: "69 quai de la rapée, 75012, Paris, France"};
var event7 = {name: "dream nations", place: "50 avenue du Président Wilson, 93200, La Plaine Saint-Denis, France"};
var event8 = {name: "zone records", place: "5 boulevard Poissonnière, 75002, Paris, France"};
var event9 = {name: "Pearson Sound b2b Call Super/ Matrixxman/Ben Vedren /Alice Revel", place: "69 quai de la rapée, 75012, Paris, France"};

var events = new Array();
events.push(event1);
events.push(event2);
events.push(event3);
events.push(event4);
events.push(event5);
events.push(event6);
events.push(event7);
events.push(event8);
events.push(event9);
